### PR TITLE
Removing BasicAuth requirement for Connections

### LINKED ISSUE #206: [BUG] Datasources deletion fails with 400 when using token auth
**Describe the bug**

Datasources deletion fails with 400 when using token auth

```
logger=authn.service t=2023-10-24T08:53:39.621212351Z level=warn msg="Failed to authenticate request" client=auth.client.basic error="[password-auth.empty] no password provided"
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.621282794Z level=info msg= error="[password-auth.empty] no password provided" remote_addr=100.127.180.0 traceID=
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.621362797Z level=info msg="Request Completed" method=DELETE path=/api/datasources/2 status=400 remote_addr=100.127.180.0 time_ms=0 duration=780.602µs size=120 referer= handler=/api/datasources/:id
```

**To Reproduce**
Create token auth context
./gdg backup connections download
./gdg backup connections upload

```
ERRO[0002] error on deleting datasource test connection with response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f84b1]
```

**Expected behavior**
Datasources deleted and uploaded normally

**Desktop (please complete the following information):**
 - GDG Version: 0.5.0
 - Grafana Version: [e.g. 10.1.5] 

**Additional context**
Another question why gdg still tries to connect with basic auth despite context is configured with token:
```
logger=authn.service t=2023-10-24T08:53:39.109379157Z level=warn msg="Failed to authenticate request" client=auth.client.basic error="[password-auth.empty] no password provided"
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.109473043Z level=info msg= error="[password-auth.empty] no password provided" remote_addr=100.127.210.128 traceID=
```

### PR DESCRIPTION
**Pull request by safaci2000**
Fixes #206

### CODE REVIEW

File: test/dashboard_integration_test.go [hunk 1]
```diff
@@ -19,77 +17,6 @@ import (
 // - Add single dashboard test -d <>
 // - Add Folder dashboard test -f <>
 
-func TestDashboardAPIKeyCRUD(t *testing.T) {
```
Comment (safaci2000) [inline test/dashboard_integration_test.go:22]: Unique test no longer needed since all code paths execute the token test now.

**Review by daldoyle — APPROVED** [review]
